// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackArrow: typeof import('./src/components/icons/BackArrow.vue')['default']
    BookCard: typeof import('./src/components/bookCard.vue')['default']
    Cards: typeof import('./src/components/cards.vue')['default']
    Dropdawn: typeof import('./src/components/Dropdawn.vue')['default']
    FileInput: typeof import('./src/components/FileInput.vue')['default']
    ForwardArrow: typeof import('./src/components/icons/ForwardArrow.vue')['default']
    Icon_with: typeof import('./src/components/Icon_with.vue')['default']
    Ingredient: typeof import('./src/components/Ingredient.vue')['default']
    InNumber: typeof import('./src/components/InNumber.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Input_accept_number: typeof import('./src/components/Input_accept_number.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Method: typeof import('./src/components/Method.vue')['default']
    OnLoading: typeof import('./src/components/onLoading.vue')['default']
    Rat_component: typeof import('./src/components/Rat_component.vue')['default']
    RateDisplay: typeof import('./src/components/RateDisplay.vue')['default']
    Rating: typeof import('./src/components/Rating.vue')['default']
    Recipe_Card: typeof import('./src/components/Recipe_Card.vue')['default']
    Review: typeof import('./src/components/Review.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signup: typeof import('./src/components/Signup.vue')['default']
    TextArea: typeof import('./src/components/TextArea.vue')['default']
  }
}

export {}
